# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 6cc9eaff454fb7f9a0c3bb8e148aa45db34a42108300af67c1f8330701afa56d15e1ac0b91b52edac5ffe2b27bc10bbf709bbbfc7995995c419c9ab0762d2f3c

test:
  secret_key_base: d44ef8a2225a9d98b475ebd510c79e393a43d64b869a35104419cf14a91fed9fa4d11ac5db453d0d587fb31f4a06d765ea45366f89ae89ab4a11c5e4bfdffb6e

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
